# Generated by Django 5.0 on 2024-01-28 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='creator',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='creator_cards', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible_offices',
            field=models.ManyToManyField(to='system.officenumber', verbose_name='Зона деятельности'),
        ),
        migrations.AddField(
            model_name='company',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_cards', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
        migrations.AddField(
            model_name='address',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='companies.company', verbose_name='Компания'),
        ),
    ]
