# Generated by Django 5.0 on 2024-02-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_bank_bankaccount_bankaccount_unique_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='unique_account',
        ),
        migrations.AddField(
            model_name='bank',
            name='regional_treasury_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер казнач. счёта терр. отд. фед. казначейства'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bic',
            field=models.CharField(max_length=11, unique=True, verbose_name='БИК или SWIFT банка/терр. отд. фед. казначейства'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер коррсчёта или единого казнач. счёта отделения ЦБР'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_account',
            field=models.CharField(max_length=34, verbose_name='Расчётный счёт или лицевой счёт в казначействе или IBAN'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('company_id', 'account_currency'), name='unique_bank_account'),
        ),
    ]
