# Generated by Django 5.0 on 2024-02-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_remove_bankaccount_unique_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='extra_info',
            field=models.TextField(blank=True, max_length=255, verbose_name='Дополнительная информация'),
        ),
    ]
