# Generated by Django 5.0 on 2024-02-08 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_bank_extra_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['id'], 'verbose_name': 'Реквизиты расчётного счёта компании', 'verbose_name_plural': 'Реквизиты банковских/казначейских счетов компаний'},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата и время обновления'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_bankaccounts', to=settings.AUTH_USER_MODEL, verbose_name='Обновил'),
        ),
    ]
