# Generated by Django 5.0 on 2024-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(blank=True, max_length=127, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='proxy_number',
            field=models.CharField(blank=True, max_length=27, verbose_name='Номер документа'),
        ),
    ]
