# Generated by Django 5.0 on 2024-02-28 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_remove_employee_unique_company_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('company_id', 'second_name', 'first_name'), name='unique_company_employee'),
        ),
    ]
