# Generated by Django 5.0 on 2024-05-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_bankaccount_current_bankaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_currency',
            field=models.CharField(blank=True, choices=[('RUB', 'Российский рубль'), ('EUR', 'Евро'), ('USD', 'Доллар США'), ('CNY', 'Китайский юань'), ('BYN', 'Белорусский рубль')], default='RUB', max_length=3, verbose_name='Валюта расчётного счёта'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='current_bankaccount',
            field=models.BooleanField(default=True, verbose_name='Текущий счёт'),
        ),
    ]
