# Generated by Django 5.0 on 2024-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_bankaccount_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='correspondent_account',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер корр. счёта или единого казнач. счёта отделения ЦБР'),
        ),
    ]
