# Generated by Django 5.0 on 2024-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_employee_is_quit'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(blank=True, max_length=40, verbose_name='Английское название'),
        ),
    ]
