# Generated by Django 5.0 on 2024-06-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_city_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(blank=True, choices=[('77', 'Moskva'), ('78', 'Saint-Peterburg'), ('50', 'Moskovskaya oblast'), ('01', 'Adygeya, Respublika'), ('02', 'Bashkortostan, Respublika'), ('03', 'Buryatia, Respublika'), ('04', 'Altay, Respublika'), ('05', 'Dagestan, Respublika'), ('06', 'Ingushskaya Respublika'), ('07', 'Kabardino-Balkarskaya Respublika'), ('08', 'Kalmykia, Respublika'), ('09', 'Karachaevo-Cherkesskaya Respublika'), ('10', 'Karelia, Respublika'), ('11', 'Komi, Respublika'), ('12', 'Mariy Ehl, Respublika'), ('13', 'Mordovia, Respublika'), ('14', 'Sakha, Respublika (Yakutiya)'), ('15', 'Severnaya Osetia, Respublika (Alania)'), ('16', 'Tatarstan, Respublika'), ('17', 'Tyva, Respublika (Tuva)'), ('18', 'Udmurtskaya Respublika'), ('19', 'Khakassiya, Respublika'), ('95', 'Chechenskaya Respublika'), ('21', 'Chuvashskaya Respublika'), ('22', 'Altayskiy Kray'), ('80', 'Zabaykalskiy Kray'), ('82', 'Kamchatskiy Kray'), ('23', 'Krasnodarskiy Kray'), ('24', 'Krasnoyarskiy Kray'), ('81', 'Permskiy Kray'), ('25', 'Primorskiy Kray'), ('26', "Stavropol'siyy Kray"), ('27', 'Khabarovskiy Kray'), ('28', 'Amurskaya oblast'), ('29', "Arkhangel'skaya oblast"), ('30', 'Astrakhanskaya oblast'), ('31', 'Belgorodskaya oblast'), ('32', 'Bryanskaya oblast'), ('33', 'Vladimirskaya oblast'), ('34', 'Volgogradskaya oblast'), ('35', 'Vologodskaya oblast'), ('36', 'Voronezhskaya oblast'), ('37', 'Ivanovskaya oblast'), ('38', 'Irkutskaya oblast'), ('39', 'Kaliningradskaya oblast'), ('40', 'Kaluzhskaya oblast'), ('42', 'Kemerovskaya oblast'), ('43', 'Kirovskaya oblast'), ('44', 'Kostromskaya oblast'), ('45', 'Kurganskaya oblast'), ('46', 'Kurskaya oblast'), ('47', 'Leningradskaya oblast'), ('48', 'Lipeckaya oblast'), ('49', 'Magadanskaya oblast'), ('51', 'Murmanskaya oblast'), ('52', 'Nizhegorodskaja oblast'), ('53', 'Novgorodskaya oblast'), ('54', 'Novosibirskaya oblast'), ('55', 'Omskaya oblast'), ('56', 'Orenburgskaya oblast'), ('57', 'Orlovskaya oblast'), ('58', 'Penzenskaya oblast'), ('60', 'Pskovskaya oblast'), ('61', 'Rostovskaya oblast'), ('62', 'Rjazanskaya oblast'), ('63', 'Samarskaya oblast'), ('64', 'Saratovskaya oblast'), ('65', 'Sakhalinskaya oblast'), ('66', 'Sverdlovskaya oblast'), ('67', 'Smolenskaya oblast'), ('68', 'Tambovskaya oblast'), ('69', 'Tverskaya oblast'), ('70', 'Tomskaya oblast'), ('71', "Tul'skaya oblast"), ('72', 'Tyumenskaya oblast'), ('73', "Ul'ianovskaya oblast"), ('74', 'Chelyabinskaya oblast'), ('76', 'Yaroslavskaya oblast'), ('79', 'Evreyskaya avtonomnaja oblast'), ('83', 'Neneckiy autonomnyy okrug'), ('86', 'Khanty-Mansiyskiy avtonomnyy okrug - Yugra'), ('87', 'Chukotskiy avtonomnyy okrug'), ('89', 'Yamalo-Neneckiy avtonomnyy okrug')], verbose_name='Область или край РФ'),
        ),
    ]
