# Generated by Django 5.0 on 2024-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_city_country_en_alter_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line_en',
            field=models.CharField(blank=True, db_index=True, max_length=256, verbose_name='Адрес на английском'),
        ),
        migrations.AddField(
            model_name='city',
            name='district_en',
            field=models.CharField(blank=True, max_length=128, verbose_name='Район или городской округ на английском'),
        ),
    ]
