# Generated by Django 5.0 on 2024-06-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_address_address_line_en_city_district_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position_en',
            field=models.CharField(blank=True, max_length=127, verbose_name='Должность на английском'),
        ),
    ]
