# Generated by Django 5.0 on 2024-02-28 21:45

import modules.applications.models.vessel
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='imo_number',
            field=modules.applications.models.vessel.CharNullField(blank=True, max_length=7, null=True, unique=True, verbose_name='Номер ИМО'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='rs_number',
            field=modules.applications.models.vessel.CharNullField(blank=True, max_length=6, null=True, unique=True, verbose_name='Регистровый номер'),
        ),
    ]
