# Generated by Django 5.0 on 2024-02-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_vessel_imo_number_alter_vessel_rs_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='me_power',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Мощность ГД'),
        ),
    ]
