# Generated by Django 5.0 on 2024-03-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_vesselextrainfo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер документв')),
            ],
            options={
                'verbose_name_plural': 'Выданные документы',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Номер формы')),
                ('form_type', models.CharField(blank=True, choices=[('CER', 'Свидетельство'), ('STA', 'Удостоверение'), ('REP', 'Акт'), ('CHE', 'Чек-лист'), ('ANN', 'Приложение'), ('AGR', 'Соглашение'), ('REG', 'Регистровая книга'), ('REC', 'Журнал'), ('RPT', 'Отчёт'), ('LET', 'Письмо'), ('MIN', 'Протокол'), ('QUR', 'Сообщение')], max_length=3, verbose_name='Тип формы')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание формы')),
            ],
            options={
                'verbose_name_plural': 'Формы документов',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='occasional_cause',
            field=models.TextField(blank=True, max_length=127, verbose_name='Причина внеочередного освидетельствования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='survey_type',
            field=models.CharField(blank=True, choices=[('ISM', 'На соответствие требованиям МКУБ'), ('ISS', 'На соответствие требованиям МК ОСПС'), ('MLC', 'На соответствие требованиям КТМС-2006'), ('DII', 'Рассмотрение II части Декларации о соответствии трудовым нормам в морском судоходстве'), ('WAC', 'Квалификационные испытания сварщиков'), ('WPS', 'Технологические процессы сварки')], default='00001', max_length=3, verbose_name='Вид освидетельствования'),
        ),
        migrations.AlterField(
            model_name='vessel',
            name='name_en',
            field=models.CharField(blank=True, max_length=55, verbose_name='Транслитерация названия судна'),
        ),
    ]
