# Generated by Django 5.0 on 2024-03-25 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_document_form_application_occasional_cause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application', verbose_name='Номер заявки'),
        ),
        migrations.AddField(
            model_name='document',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.form', verbose_name='Вид и номер формы документа'),
        ),
        migrations.AddField(
            model_name='document',
            name='item_particulars',
            field=models.TextField(blank=True, verbose_name='Описание услуги по освид. материалов и изделий'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер документа'),
        ),
    ]
