# Generated by Django 5.0 on 2024-04-20 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_account_alter_form_form_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vesselextrainfo',
            options={'verbose_name': 'Дополнительные сведения по судну и заявке', 'verbose_name_plural': 'Дополнительные сведения по судам и заявкам'},
        ),
        migrations.AlterField(
            model_name='account',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(99999999.99)], verbose_name='Стоимость услуги'),
        ),
    ]
