# Generated by Django 5.0 on 2024-06-01 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_alter_application_survey_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.vessel', verbose_name='Название судна'),
        ),
    ]
