# Generated by Django 5.0 on 2024-06-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_survey_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='survey_object',
            field=models.CharField(blank=True, choices=[('Ship', 'Судно'), ('Ship on the all parts', 'Судно по всем частям'), ('Ship on the hull part', 'Судно по корпусной части'), ('Ship on the mechanical part', 'Судно по механической части'), ('Ship on the electric-mechanical parts', 'Судно по электромеханической части'), ('Ship on the hull and mechanical parts', 'Судно по корпусной и механической частям'), ('Ship on the mechanical and electric-mechanical parts', 'Судно по механической и электромеханической частям')], default='Ship on the all parts', max_length=52, verbose_name='Объекты освидетельствования'),
        ),
    ]
