# Generated by Django 5.0 on 2024-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_application_survey_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='occasional_cause_en',
            field=models.TextField(blank=True, max_length=127, verbose_name='Уточнение сведений об услуге на английском'),
        ),
    ]
