# Generated by Django 5.0 on 2024-07-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_alter_application_survey_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='survey_object',
            field=models.CharField(blank=True, choices=[('The ship', 'Судно'), ('The ship on all parts', 'Судно по всем частям'), ('The ship on the hull part', 'Судно по корпусной части'), ('The ship on the mechanical part', 'Судно по механической части'), ('The ship on the electric-mechanical parts', 'Судно по электромеханической части'), ('The ship on the hull and mechanical parts', 'Судно по корпусной и механической частям'), ('The ship on the mechanical and electric-mechanical parts', 'Судно по механической и электромеханической частям'), ('MEEL', 'Судно по механической и электромеханической частям2')], default='The ship on all parts', max_length=56, verbose_name='Объекты освидетельствования'),
        ),
    ]
