# Generated by Django 5.0 on 2024-07-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_alter_application_survey_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='survey_object',
            field=models.CharField(blank=True, choices=[('SHIP', 'Судно'), ('ALL', 'Судно по всем частям'), ('HULL', 'Судно по корпусной части'), ('MECH', 'Судно по механической части'), ('ELEC', 'Судно по электромеханической части'), ('HUME', 'Судно по корпусной и механической частям'), ('MEEL', 'Судно по механической и электромеханической частям')], max_length=4, verbose_name='Объекты освидетельствования'),
        ),
    ]
