# Generated by Django 5.0 on 2024-07-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_alter_application_survey_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="survey_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ISM", "На соответствие требованиям МКУБ"),
                    ("ISS", "На соответствие требованиям МК ОСПС"),
                    ("MLC", "На соответствие требованиям КТМС-2006"),
                    (
                        "DII",
                        "Рассмотрение II части Декларации о соответствии трудовым нормам в морском судоходстве",
                    ),
                    ("EXP", "Расширение сферы деятельности"),
                    ("CHA", "Изменение содержания свидетельства"),
                    ("WAC", "Квалификационные испытания сварщиков"),
                    ("WPS", "Технологические процессы сварки"),
                ],
                max_length=3,
                verbose_name="Вид освидетельствования",
            ),
        ),
    ]
