# Generated by Django 5.0 on 2024-07-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_alter_application_survey_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='survey_scope',
            field=models.CharField(blank=True, choices=[('I', 'Первоначальное'), ('A', 'Ежегодное'), ('IN', 'Промежуточное'), ('S', 'Очередное'), ('R', 'Возобновляющее'), ('D', 'Подводной части судна'), ('O', 'Внеочередное'), ('C', 'Непрерывное'), ('INT', 'Временное (МКУБ, ОСПС, КТМС)'), ('ADD', 'Дополнительное (МКУБ, ОСПС, КТМС)'), ('PR', 'Первичное (СОДС, СОТПС)'), ('PL', 'Периодическое (СОДС, СОТПС)'), ('Initial', 'Первоначальное2'), ('Annual', 'Ежегодное2'), ('Intermediate', 'Промежуточное2'), ('Special', 'Очередное2'), ('Renewal', 'Возобновляющее2'), ('Bottom', 'Подводной части судна2'), ('Occasional', 'Внеочередно2е'), ('Continuous', 'Непрерывное2'), ('Interim (ISM ISPS MLC)', 'Временное (МКУБ, ОСПС, КТМС)2'), ('Additional (ISM ISPS MLC)', 'Дополнительное (МКУБ, ОСПС, КТМС)2'), ('Primary (WAC WPSAC)', 'Первичное (СОДС, СОТПС)2'), ('Periodical (WAC WPSAC)', 'Периодическое (СОДС, СОТПС)2')], max_length=25, verbose_name='Объём освидетельствования'),
        ),
    ]
