# Generated by Django 5.0 on 2024-08-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_alter_application_survey_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Номер документа или письма об одобрении ТД'),
        ),
    ]
