# Generated by Django 5.0 on 2024-08-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_alter_application_survey_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='survey_scope',
            field=models.CharField(blank=True, choices=[('I', 'Первоначальное'), ('A', 'Ежегодное'), ('IN', 'Промежуточное'), ('S', 'Очередное'), ('R', 'Возобновляющее'), ('D', 'Подводной части судна'), ('O', 'Внеочередное'), ('C', 'Непрерывное'), ('INT', 'Временное (МКУБ, ОСПС)'), ('ADD', 'Дополнительное (МКУБ, ОСПС, КТМС)'), ('PR', 'Первичное (СОДС, СОТПС, КТМС)'), ('PL', 'Периодическое (СОДС, СОТПС)')], max_length=3, verbose_name='Вид освидетельствования'),
        ),
        migrations.AlterField(
            model_name='application',
            name='survey_type',
            field=models.CharField(blank=True, choices=[('ISM', 'На соответствие требованиям МКУБ'), ('ISS', 'На соответствие требованиям МК ОСПС'), ('MLC', 'На соответствие требованиям КТМС-2006'), ('DII', 'Рассмотрение II части Декларации о соответствии трудовым нормам в морском судоходстве'), ('OSC', 'Оффшорных контейнеров'), ('TCR', 'Контейнеров-цистерн'), ('EXP', 'Расширение сферы деятельности'), ('CHA', 'Изменение содержания свидетельства'), ('WAC', 'Квалификационные испытания сварщиков'), ('WPS', 'Технологические процессы сварки')], max_length=3, verbose_name='Объём освидетельствования'),
        ),
    ]
