# Generated by Django 5.0 on 2024-10-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0033_alter_application_survey_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=30, verbose_name='Номер документа, письма об одобрении ТД или договора'),
        ),
        migrations.AlterField(
            model_name='form',
            name='form_type',
            field=models.CharField(blank=True, choices=[('ATL', 'Согласно перечню'), ('RPT', 'Отчёт'), ('CER', 'Свидетельство'), ('STA', 'Удостоверение'), ('REP', 'Акт'), ('LET', 'Письмо об одобрении'), ('AGN', 'Договор'), ('CHE', 'Чек-лист'), ('ANN', 'Приложение'), ('AGR', 'Соглашение'), ('REG', 'Регистровая книга'), ('REC', 'Журнал'), ('MIN', 'Протокол'), ('QUR', 'Сообщение')], max_length=3, verbose_name='Тип формы'),
        ),
    ]
