# Generated by Django 5.0 on 2025-03-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0034_alter_document_number_alter_form_form_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер заявки'),
        ),
    ]
