# Generated by Django 5.0 on 2024-05-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=255, verbose_name='Электронный адрес (email)'),
        ),
    ]
