# Generated by Django 5.0 on 2024-06-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_alter_feedback_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность на английском'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя на английском'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name_en',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамилия на английском'),
        ),
    ]
